Repository vshn/signalilo, pull requests merged in 2022-07, with the labels that each got.

#104 Support different Plugin Outputs per Service State
  README.md
  config/config.go
  serve.go
  webhook/hook.go
Labels: enhancement

#105 Remove duplicate command line flag
  serve.go
Labels: ignore

#106 CI: Add step to run freshly built docker image in GitHub action
  .github/workflows/test.yml
Labels: change

#107 Don't run `go get` tests for PRs from forks
  .github/workflows/test.yml
Labels: change

#108 CI: Remove EOL Go versions in GitHub action
  .github/workflows/test.yml
Labels: change
